# ref: https://openapi-generator.tech/docs/generators/typescript-axios/
generatorName: typescript-axios
outputDir: src/generated
cleanupOutput: true
inputSpec: docs/api/todo-service-api.yaml
additionalProperties:
supportsES6: true

apiPackage: src/generated/todoservice/api
modelPackage: src/generated/todoservice/model
withSeparateModelsAndApi: true
npmName: todo-service-client
# If not provided, using the version from the OpenAPI specification file.
# npmVersion: 1.0.0
enumPropertyNaming: PascalCase